// ASPF Data — AI Strategy Practice Framework
// Content for all pages

window.ASPF_DATA = {

  entryPoints: [
    {
      id: 'before',
      label: 'Before',
      color: 'var(--entry-before)',
      question: 'Should we use AI here, and how?',
      desc: 'Starting a new AI initiative — qualify the problem, select a method, map risks, define outcomes, and assess readiness.',
      cta: 'Start the intake →',
      skills: ['problem-qualification', 'ai-method-selection', 'risk-mapping', 'outcome-definition', 'readiness-audit', 'phase-routing'],
    },
    {
      id: 'during',
      label: 'During',
      color: 'var(--entry-during)',
      question: 'Are we using AI in the right ways?',
      desc: 'Mid-project recalibration — detect drift, surface emerging risks, and course-correct before failure locks in.',
      cta: 'Run an audit →',
      skills: ['mid-project-audit'],
    },
    {
      id: 'after',
      label: 'After',
      color: 'var(--entry-after)',
      question: 'Did our AI approach actually work?',
      desc: 'Post-project evaluation — measure outcomes against intentions, extract lessons, and feed forward to the next initiative.',
      cta: 'Start the retro →',
      skills: ['retrospective'],
    },
  ],

  agents: [
    {
      id: 'strategy',
      name: 'AI Strategy Lead',
      sub: 'Direction & Leadership',
      color: 'var(--role-strategy)',
      activatedWhen: 'Setting direction, making the case to leadership, evaluating where AI creates value across the product.',
      commands: ['/project:diagnose'],
      alwaysActive: false,
    },
    {
      id: 'pm',
      name: 'AI Product Manager',
      sub: 'Roadmap & Prioritization',
      color: 'var(--role-pm)',
      activatedWhen: 'Build vs. buy vs. pilot decisions, roadmap prioritization, scoping AI features and initiatives.',
      commands: ['/project:diagnose', '/project:audit'],
      alwaysActive: false,
    },
    {
      id: 'researcher',
      name: 'AI Researcher',
      sub: 'Research Practice',
      color: 'var(--role-researcher)',
      activatedWhen: 'Research method selection, evaluating AI in research practice, synthesizing AI-related findings.',
      commands: ['/project:diagnose'],
      alwaysActive: false,
    },
    {
      id: 'ethics',
      name: 'Ethics & Risk Advisor',
      sub: 'Governance & Compliance',
      color: 'var(--role-ethics)',
      activatedWhen: 'Risk mapping, governance questions, bias evaluation, compliance concerns, high-stakes domains.',
      commands: ['/project:diagnose', '/project:audit', '/project:predict'],
      alwaysActive: false,
    },
    {
      id: 'engineer',
      name: 'ML / AI Engineer',
      sub: 'Feasibility & Data',
      color: 'var(--role-engineer)',
      activatedWhen: 'Feasibility assessment, data readiness evaluation, model selection, technical constraint review.',
      commands: ['/project:diagnose', '/project:audit'],
      alwaysActive: false,
    },
    {
      id: 'change',
      name: 'Change & Enablement Lead',
      sub: 'Adoption & Readiness',
      color: 'var(--role-change)',
      activatedWhen: 'Adoption planning, team readiness assessment, resistance management, training, process change.',
      commands: ['/project:diagnose', '/project:audit'],
      alwaysActive: false,
    },
    {
      id: 'practice',
      name: 'AI Practice Lead',
      sub: 'Capability Building',
      color: 'var(--role-practice)',
      activatedWhen: 'Framework questions, capability building, cross-team AI practice decisions, methodology.',
      commands: ['/project:audit', '/project:retro'],
      alwaysActive: false,
    },
    {
      id: 'predictor',
      name: 'Predictor',
      sub: 'Always Active',
      color: 'var(--role-predictor)',
      activatedWhen: 'Runs alongside every session — pattern-matches inputs against the failure mode library and surfaces risks before the team encounters them.',
      commands: ['/project:predict', '/project:risk'],
      alwaysActive: true,
    },
  ],

  skills: [
    {
      id: 'problem-qualification',
      file: 'problem-qualification.md',
      entryPoint: 'before',
      step: 1,
      goal: 'Go / No-go on using AI for this problem.',
      output: 'Problem Qualification Record — scored and documented.',
      unlocks: 'AI Method Selection. Nothing proceeds without this.',
      desc: 'Determine whether a problem is genuinely worth solving with AI before committing any method, tool, or resource.',
    },
    {
      id: 'ai-method-selection',
      file: 'ai-method-selection.md',
      entryPoint: 'before',
      step: 2,
      goal: 'Which AI method to use, and whether to build, buy, or integrate it.',
      output: 'AI Method Selection Brief — method, rationale, data requirements.',
      unlocks: 'Risk Mapping and Readiness Audit.',
      desc: 'Select the right AI approach for a validated problem before any build, buy, or pilot decision is made.',
    },
    {
      id: 'risk-mapping',
      file: 'risk-mapping.md',
      entryPoint: 'before',
      step: 3,
      goal: 'Whether and how to proceed given the risk profile.',
      output: 'AI Risk Register — scored risks with mitigations and owners.',
      unlocks: 'A defensible path forward. Feeds into APDF as phase-level constraints.',
      desc: 'Identify and structure AI-specific risks across technical, ethical, organizational, and legal dimensions.',
    },
    {
      id: 'outcome-definition',
      file: 'outcome-definition.md',
      entryPoint: 'before',
      step: 4,
      goal: 'What success looks like — specific enough that anyone can judge it.',
      output: 'Outcome Brief — hypothesis statement, primary metric, guardrails.',
      unlocks: 'Accountability. The readiness audit is only meaningful with a defined destination.',
      desc: 'Define measurable outcomes and success criteria before any AI is built, bought, or deployed.',
    },
    {
      id: 'readiness-audit',
      file: 'readiness-audit.md',
      entryPoint: 'before',
      step: 5,
      goal: 'Whether the team is ready to commit — and if not, what must change first.',
      output: 'Readiness Score (0–100) across people, data, tooling, process.',
      unlocks: 'Informed commitment. Gaps become conditions, not surprises.',
      desc: 'Audit team readiness across four dimensions before any significant AI investment is committed.',
    },
    {
      id: 'phase-routing',
      file: 'phase-routing.md',
      entryPoint: 'before',
      step: 6,
      goal: 'Which APDF phase to enter, with what context and constraints.',
      output: 'APDF Handoff Brief — strategy becomes design input.',
      unlocks: 'Continuity between ASPF and APDF. Run via /project:handoff.',
      desc: 'Translate completed ASPF outputs into an APDF-ready brief — the bridge between strategy and design.',
    },
    {
      id: 'mid-project-audit',
      file: 'mid-project-audit.md',
      entryPoint: 'during',
      step: 1,
      goal: 'Continue, pivot, or stop — with a rationale and owned actions.',
      output: 'Mid-Project Audit Report — drift assessment, metric trajectory, course correction.',
      unlocks: 'The ability to course-correct before failure is locked in.',
      desc: 'Detect drift across five categories and surface emerging risks while there is still time to respond.',
    },
    {
      id: 'retrospective',
      file: 'retrospective.md',
      entryPoint: 'after',
      step: 1,
      goal: 'What to carry forward, change, and watch for in the next initiative.',
      output: 'Retrospective Report + Feed-Forward Block for the next Before session.',
      unlocks: 'Compounding improvement. The learning loop closes here.',
      desc: 'Evaluate outcomes against intentions, audit process adherence, and generate inputs for the next cycle.',
    },
    {
      id: 'failure-mode-library',
      file: 'failure-mode-library.md',
      entryPoint: 'all',
      step: null,
      goal: 'Pattern library for the Predictor — loaded in every session.',
      output: 'Predictive Risk Report when run via /project:predict.',
      unlocks: 'Proactive failure prevention across all entry points.',
      desc: 'Eleven documented AI strategy failure modes with early signals and interventions. The Predictor\'s reference library.',
    },
  ],

  commands: [
    { cmd: '/project:diagnose', desc: 'Start a Before session — full decision tree from scratch.' },
    { cmd: '/project:audit',    desc: 'Start a During session — mid-project recalibration.' },
    { cmd: '/project:retro',    desc: 'Start an After session — retrospective evaluation.' },
    { cmd: '/project:predict',  desc: 'Run the Predictor standalone against current context.' },
    { cmd: '/project:risk',     desc: 'Surface the current risk profile.' },
    { cmd: '/project:handoff',  desc: 'Generate an APDF-ready brief from ASPF outputs.' },
    { cmd: '/project:update-readme', desc: 'Sync README.md with current framework state.' },
  ],

  failureModes: [
    { id: 'FM-01', name: 'Solution-First Thinking',      category: 'Problem Definition', when: 'Immediately',        signal: 'Tool named before problem stated.' },
    { id: 'FM-02', name: 'Problem-Outcome Disconnect',   category: 'Problem Definition', when: 'Outcome definition', signal: 'Primary metric is an AI system metric, not a business outcome.' },
    { id: 'FM-03', name: 'Scope Creep at Definition',    category: 'Problem Definition', when: 'Method selection',   signal: 'Problem statement grows with each iteration.' },
    { id: 'FM-04', name: 'Method-Problem Mismatch',      category: 'Technical',          when: 'Pilot / early build',signal: 'Method chosen by familiarity, not problem type.' },
    { id: 'FM-05', name: 'Data Readiness Overestimation',category: 'Technical',          when: 'Early build',        signal: '"We have lots of data" — without verification.' },
    { id: 'FM-06', name: 'Evaluation Gap',               category: 'Technical',          when: 'Build and pilot',    signal: '"We\'ll know it when we see it."' },
    { id: 'FM-07', name: 'Accountability Gap',           category: 'Organizational',     when: 'Production',         signal: 'No named owner for the AI system in production.' },
    { id: 'FM-08', name: 'The Pilot Trap',               category: 'Organizational',     when: 'Scaling',            signal: 'Pilot conditions significantly differ from production.' },
    { id: 'FM-09', name: 'Change Resistance',            category: 'Organizational',     when: 'Activation',         signal: 'No change management plan alongside the technical plan.' },
    { id: 'FM-10', name: 'Undetected Bias',              category: 'Ethics & Fairness',  when: 'Production',         signal: 'No bias evaluation conducted before deployment.' },
    { id: 'FM-11', name: 'Opacity at Scale',             category: 'Ethics & Fairness',  when: 'Production',         signal: 'No explainability mechanism for consequential decisions.' },
  ],
};
