// ASPF Data — AI Strategy Practice Framework
// Internal practice methodology — not client-facing

window.ASPF_DATA = {

  // ── AI-Native Enterprise Foundation ──────────────────────────────────────
  aiNativeEnterprise: {
    definition: 'An AI-native organization is designed from the ground up to operate and create value through AI agents — where agents are the default workers across front, middle, and back-office processes.',
    shifts: [
      {
        id: 'agents-work',
        label: 'Agents do the work',
        sub: 'Humans set direction and guide',
        desc: 'Agents handle execution by default. The organization flattens around individual contributors and directly responsible individuals; middle management layers shrink.',
      },
      {
        id: 'legible',
        label: 'The entire company is legible to AI',
        sub: 'Data, processes, and context are unified',
        desc: 'All company data and processes are captured, structured, and unified so agents can read the full context of the business and operate autonomously.',
      },
      {
        id: 'closed-loop',
        label: 'The company runs in a closed loop',
        sub: 'Sense, decide, act, learn — continuously',
        desc: 'Every workflow runs as a loop — it senses what\'s happening, decides, acts, checks the result, and feeds what it learned back in for improvements.',
      },
    ],
  },

  // ── Six AI Practice Pillars ───────────────────────────────────────────────
  pillars: [
    {
      id: 'p1',
      number: '01',
      name: 'AI Value & Tech Strategy',
      shortName: 'Strategy',
      color: '#6366F1', // indigo
      desc: 'Define the AI strategy, operating model, and architecture so clients know where to invest, what to build first, and how to measure value.',
      focus: [
        'Data and AI platform strategy',
        'Process redesign blueprinting',
        'Roadmap and implementation plan development',
        'Tools and application rationalization',
        'Investment case',
      ],
      skills: {
        before: ['stakeholder-alignment', 'maturity-model', 'outcome-definition', 'problem-qualification'],
        during: ['mid-project-audit'],
        after: ['retrospective'],
      },
    },
    {
      id: 'p2',
      number: '02',
      name: 'AI Data Foundation',
      shortName: 'Data',
      color: '#0EA5E9', // sky
      desc: 'Build the data backbone that AI runs on so agents and models can access the full context of the business.',
      focus: [
        'Data architecture and lakehouse build',
        'Pipelines, quality, and lineage',
        'Access controls and governance',
        'Knowledge base and company brain structuring',
      ],
      skills: {
        before: ['data-strategy', 'readiness-audit', 'responsible-ai'],
        during: ['model-monitoring', 'mid-project-audit'],
        after: ['retrospective'],
      },
    },
    {
      id: 'p3',
      number: '03',
      name: 'AI Rapid Innovation Garage',
      shortName: 'Innovation',
      color: '#10B981', // emerald
      desc: 'Design, build, and launch AI agents through rapid development and experimentation — so clients see working outcomes in weeks, not months.',
      focus: [
        'Process, workflow, and use-case discovery and prioritization',
        'Process redesign around agents',
        'Agent and application build',
        'First production deployment and adoption',
      ],
      skills: {
        before: ['use-case-prioritization', 'problem-qualification', 'agent-design', 'ai-method-selection', 'responsible-ai', 'stakeholder-alignment'],
        during: ['mid-project-audit', 'user-feedback-loops'],
        after: ['retrospective'],
      },
    },
    {
      id: 'p4',
      number: '04',
      name: 'AI Governance',
      shortName: 'Governance',
      color: '#F59E0B', // amber
      desc: 'Implement policies, controls, guardrails, and human oversight into AI systems.',
      focus: [
        'Responsible AI policy and operating model implementation',
        'Model and agent inventory management',
        'Risk reviews and audits',
        'Continuous compliance monitoring',
      ],
      products: ['Token Optimization (workshop)', 'Operating Model (workshop)'],
      skills: {
        before: ['responsible-ai', 'risk-mapping', 'stakeholder-alignment', 'outcome-definition'],
        during: ['model-monitoring', 'mid-project-audit'],
        after: ['retrospective'],
      },
    },
    {
      id: 'p5',
      number: '05',
      name: 'AI Factory',
      shortName: 'Factory',
      color: '#EF4444', // red
      desc: 'Industrialize AI delivery and operations so AI systems run reliably, repeatably, and at enterprise scale.',
      focus: [
        'Reusable patterns and components',
        'MLOps and AgentOps pipelines',
        'Closed-loop monitoring and evals',
        'Cross-business-unit roll-out',
      ],
      products: ['HR/Employee Operations', 'Customer Operations'],
      skills: {
        before: ['mlops-readiness', 'operating-model', 'readiness-audit', 'outcome-definition', 'risk-mapping'],
        during: ['model-monitoring', 'user-feedback-loops', 'mid-project-audit'],
        after: ['retrospective', 'maturity-model'],
      },
    },
    {
      id: 'p6',
      number: '06',
      name: 'Run & Enhance',
      shortName: 'Run',
      color: '#8B5CF6', // violet
      desc: 'Operate the AI-native organization post-launch and continuously improve the system and outcomes.',
      focus: [
        'L1–L3 support for agents and applications',
        'SLA-backed managed services',
        'Continuous process and system tuning',
        'Ongoing value capture and reporting',
      ],
      skills: {
        before: ['managed-service-model', 'outcome-definition', 'risk-mapping', 'responsible-ai'],
        during: ['model-monitoring', 'user-feedback-loops', 'mid-project-audit'],
        after: ['retrospective', 'maturity-model'],
      },
    },
  ],

  // ── Entry Points (lifecycle) ──────────────────────────────────────────────
  entryPoints: [
    {
      id: 'before',
      label: 'Before',
      color: 'var(--entry-before)',
      question: 'Starting or scoping an engagement',
      desc: 'Qualify, plan, and prepare before committing resources.',
    },
    {
      id: 'during',
      label: 'During',
      color: 'var(--entry-during)',
      question: 'Active engagement — checking in',
      desc: 'Audit progress, detect drift, surface risks.',
    },
    {
      id: 'after',
      label: 'After',
      color: 'var(--entry-after)',
      question: 'Engagement concluded — evaluating',
      desc: 'Measure outcomes, extract lessons, feed forward.',
    },
  ],

  // ── Skills ────────────────────────────────────────────────────────────────
  skills: [
    {
      id: 'discovery',
      file: 'discovery.md',
      entryPoint: 'before',
      goal: 'Where the client is across all six pillars, what the gaps are, and in what sequence the work should proceed.',
      output: 'Master Client Brief — six-pillar assessment, gap analysis, prioritized roadmap, client communication points.',
      unlocks: 'Every pillar engagement. No pillar work begins without a discovery brief.',
      desc: 'Three-act discovery: prepare the practitioner, facilitate the workshop, synthesize findings into the master brief.',
      pillars: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
      isPrimary: true,
    },
      file: 'problem-qualification.md',
      entryPoint: 'before',
      goal: 'Go / No-go on using AI for this problem.',
      output: 'Problem Qualification Record — scored and documented.',
      unlocks: 'AI Method Selection.',
      desc: 'Determine whether a problem is worth solving with AI before committing any method or resource.',
      pillars: ['p1', 'p3'],
    },
    {
      id: 'ai-method-selection',
      file: 'ai-method-selection.md',
      entryPoint: 'before',
      goal: 'Which AI method to use, and whether to build, buy, or integrate.',
      output: 'AI Method Selection Brief.',
      unlocks: 'Risk Mapping and Readiness Audit.',
      desc: 'Select the right AI approach for a validated problem.',
      pillars: ['p1', 'p3'],
    },
    {
      id: 'responsible-ai',
      file: 'responsible-ai.md',
      entryPoint: 'before',
      goal: 'Whether this initiative meets responsible AI obligations.',
      output: 'Responsible AI Assessment — five principles, regulatory mapping, sign-off record.',
      unlocks: 'Defensible governance record. Required by EU AI Act, ISO 42001, NIST AI RMF.',
      desc: 'Five-principle responsible AI checklist — fairness, accountability, transparency, privacy, safety.',
      pillars: ['p4', 'p2', 'p3'],
    },
    {
      id: 'risk-mapping',
      file: 'risk-mapping.md',
      entryPoint: 'before',
      goal: 'Whether and how to proceed given the risk profile.',
      output: 'AI Risk Register — scored risks with mitigations and owners.',
      unlocks: 'A defensible path forward. Feeds into APDF as phase-level constraints.',
      desc: 'Identify and structure AI-specific risks across technical, ethical, organizational, and legal dimensions.',
      pillars: ['p4', 'p1', 'p6'],
    },
    {
      id: 'outcome-definition',
      file: 'outcome-definition.md',
      entryPoint: 'before',
      goal: 'What success looks like — specific enough that anyone can judge it.',
      output: 'Outcome Brief — hypothesis statement, primary metric, guardrails.',
      unlocks: 'Accountability. Makes the readiness audit meaningful.',
      desc: 'Define measurable outcomes and success criteria before any AI is built or deployed.',
      pillars: ['p1', 'p5', 'p6'],
    },
    {
      id: 'readiness-audit',
      file: 'readiness-audit.md',
      entryPoint: 'before',
      goal: 'Whether the team is ready to commit — and if not, what must change.',
      output: 'Readiness Score (0–100) across people, data, tooling, process.',
      unlocks: 'Informed commitment. Gaps become conditions, not surprises.',
      desc: 'Audit team readiness across four dimensions before any significant AI investment.',
      pillars: ['p2', 'p5'],
    },
    {
      id: 'data-strategy',
      file: 'data-strategy.md',
      entryPoint: 'before',
      goal: 'Whether the data strategy is sufficient to proceed.',
      output: 'Data Strategy Document — inventory, governance, lineage, consent, quality plan.',
      unlocks: 'Confidence the AI system\'s data foundation is sound. Prevents FM-05.',
      desc: 'Define how data will be sourced, governed, used, and maintained.',
      pillars: ['p2'],
    },
    {
      id: 'stakeholder-alignment',
      file: 'stakeholder-alignment.md',
      entryPoint: 'before',
      goal: 'Whether the organization is aligned enough to proceed.',
      output: 'Stakeholder Alignment Map and Leadership Case.',
      unlocks: 'Organizational permission to proceed.',
      desc: 'Map stakeholders, identify resistance, and build the leadership case.',
      pillars: ['p1', 'p3', 'p4'],
    },
    {
      id: 'maturity-model',
      file: 'maturity-model.md',
      entryPoint: 'before',
      goal: 'Where the AI practice sits today — and where to invest to move it forward.',
      output: 'AI Practice Maturity Assessment — six dimensions, 12-month roadmap.',
      unlocks: 'A strategic foundation for practice improvement.',
      desc: 'Assess the team\'s sustained capability to run AI initiatives across six dimensions.',
      pillars: ['p1', 'p5', 'p6'],
    },
    {
      id: 'mid-project-audit',
      file: 'mid-project-audit.md',
      entryPoint: 'during',
      goal: 'Continue, pivot, or stop — with rationale and owned actions.',
      output: 'Mid-Project Audit Report — drift assessment, metric trajectory, course correction.',
      unlocks: 'The ability to course-correct before failure is locked in.',
      desc: 'Detect drift across five categories and surface emerging risks.',
      pillars: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
    },
    {
      id: 'model-monitoring',
      file: 'model-monitoring.md',
      entryPoint: 'during',
      goal: 'Whether the AI system is performing as intended in production.',
      output: 'Model Monitoring Plan — five-layer monitoring with alert thresholds.',
      unlocks: 'Proactive operational control. Prevents silent failure.',
      desc: 'Design and run ongoing monitoring across input drift, output drift, performance, fairness, and operational health.',
      pillars: ['p2', 'p4', 'p5', 'p6'],
    },
    {
      id: 'user-feedback-loops',
      file: 'user-feedback-loops.md',
      entryPoint: 'during',
      goal: 'Whether the AI system is working for users.',
      output: 'User Feedback Plan — three-layer collection with analysis cadence.',
      unlocks: 'The human signal layer that model monitoring can\'t provide.',
      desc: 'Design structured feedback mechanisms that capture how users experience the AI system.',
      pillars: ['p3', 'p5', 'p6'],
    },
    {
      id: 'retrospective',
      file: 'retrospective.md',
      entryPoint: 'after',
      goal: 'What to carry forward, change, and watch for in the next engagement.',
      output: 'Retrospective Report + Feed-Forward Block.',
      unlocks: 'Compounding improvement across engagements.',
      desc: 'Evaluate outcomes against intentions, audit process, and generate inputs for the next cycle.',
      pillars: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
    },
    {
      id: 'phase-routing',
      file: 'phase-routing.md',
      entryPoint: 'before',
      goal: 'Which APDF phase to enter with what context and constraints.',
      output: 'APDF Handoff Brief — strategy becomes design input.',
      unlocks: 'Continuity between ASPF and APDF.',
      desc: 'Translate ASPF outputs into an APDF-ready brief — the bridge between strategy and design.',
      pillars: ['p1', 'p3'],
    },
    {
      id: 'use-case-prioritization',
      file: 'use-case-prioritization.md',
      entryPoint: 'before',
      goal: 'Which use case to build first — and in what sequence to build the rest.',
      output: 'Use-Case Priority Matrix — every idea scored across four dimensions, ranked, and sequenced.',
      unlocks: 'A clear, defensible starting point for the Innovation Garage build.',
      desc: 'Evaluate and sequence AI use cases so the client builds the right thing first and sees working outcomes quickly.',
      pillars: ['p3'],
    },
    {
      id: 'agent-design',
      file: 'agent-design.md',
      entryPoint: 'before',
      goal: 'What the agent does, how it does it, what it doesn\'t do, and how humans stay in control.',
      output: 'Agent Design Specification — complete behavioral, technical, and governance definition.',
      unlocks: 'Engineering clarity. Stakeholder alignment. A testable definition of success.',
      desc: 'Define the shape, behavior, and boundaries of an AI agent before engineering starts.',
      pillars: ['p3'],
    },
    {
      id: 'mlops-readiness',
      file: 'mlops-readiness.md',
      entryPoint: 'before',
      goal: 'Whether the client is ready to industrialize AI delivery — and what must be built first.',
      output: 'MLOps Readiness Assessment — six dimensions scored with a phased engagement plan.',
      unlocks: 'A clear scope for the AI Factory engagement. Prevents building on an inadequate foundation.',
      desc: 'Assess readiness to industrialize AI delivery through MLOps and AgentOps infrastructure.',
      pillars: ['p5'],
    },
    {
      id: 'operating-model',
      file: 'operating-model.md',
      entryPoint: 'before',
      goal: 'How the organization needs to be structured to operate AI sustainably at scale.',
      output: 'AI Operating Model Design — roles, governance, decision rights, and workforce transition.',
      unlocks: 'The organizational foundation for the AI Factory. Directly enables the three AI-native shifts.',
      desc: 'Define how AI fits into the client\'s operating model — roles, governance, decision rights, and workflows.',
      pillars: ['p1', 'p5'],
    },
    {
      id: 'managed-service-model',
      file: 'managed-service-model.md',
      entryPoint: 'before',
      goal: 'What the Run & Enhance engagement covers, at what service level, and how value is demonstrated continuously.',
      output: 'Managed Service Model Design — support tiers, SLAs, improvement cadence, value reporting.',
      unlocks: 'The operational contract for AI systems post-launch. Prevents silent degradation.',
      desc: 'Design the managed service model for operating AI systems — support, maintenance, improvement, and value reporting.',
      pillars: ['p6'],
    },
    {
      id: 'failure-mode-library',
      file: 'failure-mode-library.md',
      entryPoint: 'all',
      goal: 'Pattern library for the Predictor — loaded in every session.',
      output: 'Predictive Risk Report via /project:predict.',
      unlocks: 'Proactive failure prevention across all pillars and lifecycle stages.',
      desc: 'Eleven documented AI strategy failure modes with early signals and interventions.',
      pillars: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
    },
  ],

  // ── Commands ──────────────────────────────────────────────────────────────
  commands: [
    { cmd: '/project:discover',  desc: 'Start a discovery session — prerequisite to all six pillar engagements.' },
    { cmd: '/project:diagnose',  desc: 'Start a Before session — full decision tree from scratch.' },
    { cmd: '/project:audit',    desc: 'Start a During session — mid-engagement recalibration.' },
    { cmd: '/project:retro',    desc: 'Start an After session — retrospective evaluation.' },
    { cmd: '/project:predict',  desc: 'Run the Predictor standalone against current context.' },
    { cmd: '/project:risk',     desc: 'Surface the current risk profile.' },
    { cmd: '/project:handoff',  desc: 'Generate an APDF-ready brief from ASPF outputs.' },
    { cmd: '/project:deck',     desc: 'Generate a stakeholder PowerPoint from any skill artifact.' },
    { cmd: '/project:update-readme', desc: 'Sync README.md with current framework state.' },
  ],

  // ── Failure modes ─────────────────────────────────────────────────────────
  failureModes: [
    { id: 'FM-01', name: 'Solution-First Thinking',       category: 'Problem Definition', when: 'Immediately',        signal: 'Tool named before problem stated.' },
    { id: 'FM-02', name: 'Problem-Outcome Disconnect',    category: 'Problem Definition', when: 'Outcome definition',  signal: 'Primary metric is an AI system metric, not a business outcome.' },
    { id: 'FM-03', name: 'Scope Creep at Definition',     category: 'Problem Definition', when: 'Method selection',    signal: 'Problem statement grows with each iteration.' },
    { id: 'FM-04', name: 'Method-Problem Mismatch',       category: 'Technical',          when: 'Pilot / early build', signal: 'Method chosen by familiarity, not problem type.' },
    { id: 'FM-05', name: 'Data Readiness Overestimation', category: 'Technical',          when: 'Early build',         signal: '"We have lots of data" — without verification.' },
    { id: 'FM-06', name: 'Evaluation Gap',                category: 'Technical',          when: 'Build and pilot',     signal: '"We\'ll know it when we see it."' },
    { id: 'FM-07', name: 'Accountability Gap',            category: 'Organizational',     when: 'Production',          signal: 'No named owner for the AI system in production.' },
    { id: 'FM-08', name: 'The Pilot Trap',                category: 'Organizational',     when: 'Scaling',             signal: 'Pilot conditions significantly differ from production.' },
    { id: 'FM-09', name: 'Change Resistance',             category: 'Organizational',     when: 'Activation',          signal: 'No change management plan alongside the technical plan.' },
    { id: 'FM-10', name: 'Undetected Bias',               category: 'Ethics & Fairness',  when: 'Production',          signal: 'No bias evaluation conducted before deployment.' },
    { id: 'FM-11', name: 'Opacity at Scale',              category: 'Ethics & Fairness',  when: 'Production',          signal: 'No explainability mechanism for consequential decisions.' },
  ],
};
